
  CREATE OR REPLACE FORCE VIEW "SIS_OWNER"."COM_ORDENES_COMPRAS_V" ("ID", "SEGORG_ID", "COMCON_ID", "COMADJ_ID", "COMPED_ID", "COMPRV_ID", "CODIGO", "FECHA_GENERACION", "TIPO_ENTREGA", "PRORROGA_SN", "MONTO", "SALDO", "MONTO_DESCUENTO", "OBSERVACION", "FECHA_MAX_CALIFICACION", "FECHA_ULTIMA_ENTREGA", "DATOS_CONTRATO", "DATE_CREATED", "DATE_MODIFIED", "CREATED_BY", "CREATED_BY_NOMBRE", "MODIFIED_BY", "MODIFIED_BY_NOMBRE", "FECHA_VISUALIZA", "COMPRV_CUIT", "COMPRV_NOMBRE", "COMPRV_DESCRIPCION_ACTIVIDAD", "COMPRV_EMAIL", "COMPRV_CONDICION_IB", "COMOCE_ID", "COMOCE_FECHA", "COMOCE_ESTADO", "COMOCE_ESTADO_DESC", "COMOCE_MOTIVO", "COMCTT_ID", "COMCON_CODIGO", "COMCON_OBJETO", "COMCON_MONTO_PRESUPUESTO", "COMCON_FORMA_PAGO", "COMCON_PLAZO_ENTREGA_DIAS", "COMCON_VIGENCIA_OFERTA_DIAS", "COMCON_METODO_ADJUDICACION", "COMCON_FECHA_PUBLICACION", "COMCON_FECHA_INICIO_PROPUESTA", "COMCON_FECHA_FIN_PROPUESTA", "COMCON_OBSERVACIONES", "COMADJ_FECHA_GENERACION", "COMADJ_OBSERVACION", "COMADJ_SITUACION", "COMPED_CODIGO", "COMPED_FECHA_SOLICITUD", "COMECO_ID", "COMECO_ID_PADRE", "COMCOB_ID", "COMPED_EJERCICIO", "COMPED_CONTRATANTE", "COMPED_SOLICITANTE", "COMPED_DESCRIPCION", "COMPED_CONTACTO", "COMPED_COMDOM_ID", "COMPED_TIPO_ENTREGA", "COMPED_PLAZO_ENTREGA_CANTIDAD", "COMPED_PLAZO_ENTREGA_UNIDAD", "COMPED_FECHA_ENTREGA", "COMPED_PERIODO_ENTREGA", "COMPED_PRECIO", "COMPED_PARTIDA_PRESUPUESTARIA", "COMPED_EXPEDIENTE", "COMPED_RESOLUCION", "COMPED_OBSERVACIONES", "COMDMT_ID", "COMDOM_PAIS", "COMDOM_PROVINCIA", "COMDOM_DEPARTAMENTO", "COMDOM_LOCALIDAD", "COMDOM_CALLE", "COMDOM_NUMERO_CASA", "COMDOM_PISO", "COMDOM_DPTO", "COMDOM_OBSERVACION", "COMDOM_CODIGO_POSTAL", "COMDOM_TELEFONO_CODIGO_AREA", "COMDOM_TELEFONO_NUMERO", "COMDOM_FAX_CODIGO_AREA", "COMDOM_FAX_NUMERO", "COMCTT_CODIGO", "COMCTT_NOMBRE", "COMCTT_FORMATO_ORDEN", "COMCTT_LIMITE_MAX_CALIFICAR", "COMCNT_ID", "COMECC_ID", "COMECO_CODIGO", "COMECO_NOMBRE", "COMECO_EMAIL", "COMPEE_ID", "COMPEE_FECHA", "COMPEE_ESTADO", "COMPEE_MOTIVO", "COMPEE_ESTADO_DESC", "COMCOE_ID", "COMCOE_FECHA", "COMCOE_ESTADO", "COMCOE_MOTIVO", "COMCOE_ESTADO_DESC", "COMECC_CODIGO", "COMECC_NOMBRE") AS 
  SELECT COMOCM.ID ID
,COMOCM.SEGORG_ID SEGORG_ID
,COMOCM.COMCON_ID COMCON_ID
,COMOCM.COMADJ_ID COMADJ_ID
,COMOCM.COMPED_ID COMPED_ID
,COMOCM.COMPRV_ID COMPRV_ID
,COMOCM.CODIGO CODIGO
,COMOCM.FECHA_GENERACION FECHA_GENERACION
,COMOCM.TIPO_ENTREGA TIPO_ENTREGA
,COMOCM.PRORROGA_SN PRORROGA_SN
,COMOCM.MONTO MONTO
,COMOCM.SALDO SALDO
,COMOCM.MONTO_DESCUENTO MONTO_DESCUENTO
,COMOCM.OBSERVACION OBSERVACION
,COMOCM.FECHA_MAX_CALIFICACION FECHA_MAX_CALIFICACION
,COMOCM.FECHA_ULTIMA_ENTREGA FECHA_ULTIMA_ENTREGA
,COMOCM.DATOS_CONTRATO DATOS_CONTRATO
,COMOCM.DATE_CREATED DATE_CREATED
,COMOCM.DATE_MODIFIED DATE_MODIFIED
,COMOCM.CREATED_BY CREATED_BY
,NVL(SEG_PKG.OBTN_SEGUSU_NOMBRE(COMOCM.CREATED_BY),COMOCM.CREATED_BY)
,COMOCM.MODIFIED_BY MODIFIED_BY
,NVL(SEG_PKG.OBTN_SEGUSU_NOMBRE(COMOCM.MODIFIED_BY),COMOCM.MODIFIED_BY)
,COMOCM.FECHA_VISUALIZA FECHA_VISUALIZA
,COMPRV.CUIT COMPRV_CUIT
,COMPRV.NOMBRE COMPRV_NOMBRE
,COMPRV.DESCRIPCION_ACTIVIDAD COMPRV_DESCRIPCION_ACTIVIDAD
,COMPRV.EMAIL COMPRV_EMAIL
,COMPRV.CONDICION_IB COMPRV_CONDICION_IB
,COMOCE.ID COMOCE_ID
,COMOCE.FECHA COMOCE_FECHA
,COMOCE.ESTADO COMOCE_ESTADO
,(SELECT c.rv_abbreviation FROM cg_ref_codes c WHERE c.rv_domain = 'COM_ORDENES_COMPRAS_EST.ESTADO' AND c.rv_low_value = comoce.ESTADO)
,COMOCE.MOTIVO COMOCE_MOTIVO
,COMCON.COMCTT_ID COMCTT_ID
,COMCON.CODIGO COMCON_CODIGO
,COMCON.OBJETO COMCON_OBJETO
,COMCON.MONTO_PRESUPUESTO COMCON_MONTO_PRESUPUESTO
,COMCON.FORMA_PAGO COMCON_FORMA_PAGO
,COMCON.PLAZO_ENTREGA_DIAS COMCON_PLAZO_ENTREGA_DIAS
,COMCON.VIGENCIA_OFERTA_DIAS COMCON_VIGENCIA_OFERTA_DIAS
,COMCON.METODO_ADJUDICACION COMCON_METODO_ADJUDICACION
,COMCON.FECHA_PUBLICACION COMCON_FECHA_PUBLICACION
,COMCON.FECHA_INICIO_PROPUESTA COMCON_FECHA_INICIO_PROPUESTA
,COMCON.FECHA_FIN_PROPUESTA COMCON_FECHA_FIN_PROPUESTA
,COMCON.OBSERVACIONES COMCON_OBSERVACIONES
,COMADJ.FECHA_GENERACION COMADJ_FECHA_GENERACION
,COMADJ.OBSERVACION COMADJ_OBSERVACION
,COMADJ.SITUACION COMADJ_SITUACION
,COMPED.CODIGO COMPED_CODIGO
,COMPED.FECHA_SOLICITUD COMPED_FECHA_SOLICITUD
,COMPED.COMECO_ID COMECO_ID
,NVL((select comeco_id_padre from com_contratantes_vinc where comeco_id_hijo = comped.comeco_id) ,comped.comeco_id)
,COMPED.COMCOB_ID COMCOB_ID
,COMPED.EJERCICIO COMPED_EJERCICIO
,COMPED.CONTRATANTE COMPED_CONTRATANTE
,COMPED.SOLICITANTE COMPED_SOLICITANTE
,COMPED.DESCRIPCION COMPED_DESCRIPCION
,COMPED.CONTACTO COMPED_CONTACTO
,COMPED.COMDOM_ID COMPED_COMDOM_ID
,COMPED.TIPO_ENTREGA COMPED_TIPO_ENTREGA
,COMPED.PLAZO_ENTREGA_CANTIDAD COMPED_PLAZO_ENTREGA_CANTIDAD
,COMPED.PLAZO_ENTREGA_UNIDAD COMPED_PLAZO_ENTREGA_UNIDAD
,COMPED.FECHA_ENTREGA COMPED_FECHA_ENTREGA
,COMPED.PERIODO_ENTREGA COMPED_PERIODO_ENTREGA
,COMPED.PRECIO COMPED_PRECIO
,COMPED.PARTIDA_PRESUPUESTARIA COMPED_PARTIDA_PRESUPUESTARIA
,COMPED.EXPEDIENTE COMPED_EXPEDIENTE
,COMPED.RESOLUCION COMPED_RESOLUCION
,COMPED.OBSERVACIONES COMPED_OBSERVACIONES
,COMDOM.COMDMT_ID COMDMT_ID
,COMDOM.PAIS COMDOM_PAIS
,COMDOM.PROVINCIA COMDOM_PROVINCIA
,COMDOM.DEPARTAMENTO COMDOM_DEPARTAMENTO
,COMDOM.LOCALIDAD COMDOM_LOCALIDAD
,COMDOM.CALLE COMDOM_CALLE
,COMDOM.NUMERO_CASA COMDOM_NUMERO_CASA
,COMDOM.PISO COMDOM_PISO
,COMDOM.DPTO COMDOM_DPTO
,COMDOM.OBSERVACION COMDOM_OBSERVACION
,COMDOM.CODIGO_POSTAL COMDOM_CODIGO_POSTAL
,COMDOM.TELEFONO_CODIGO_AREA COMDOM_TELEFONO_CODIGO_AREA
,COMDOM.TELEFONO_NUMERO COMDOM_TELEFONO_NUMERO
,COMDOM.FAX_CODIGO_AREA COMDOM_FAX_CODIGO_AREA
,COMDOM.FAX_NUMERO COMDOM_FAX_NUMERO
,COMCTT.CODIGO COMCTT_CODIGO
,COMCTT.NOMBRE COMCTT_NOMBRE
,COMCTT.FORMATO_ORDEN COMCTT_FORMATO_ORDEN
,COMCTT.LIMITE_MAX_CALIFICAR COMCTT_LIMITE_MAX_CALIFICAR
,COMECO.COMCNT_ID COMCNT_ID
,COMECO.COMECC_ID COMECC_ID
,COMECO.CODIGO COMECO_CODIGO
,COMECO.NOMBRE COMECO_NOMBRE
,COMECO.EMAIL COMECO_EMAIL
,COMPEE.ID COMPEE_ID
,COMPEE.FECHA COMPEE_FECHA
,COMPEE.ESTADO COMPEE_ESTADO
,COMPEE.MOTIVO COMPEE_MOTIVO
,(SELECT c.rv_abbreviation FROM cg_ref_codes c WHERE c.rv_domain = 'COM_PEDIDOS_EST.ESTADO' AND c.rv_low_value = compee.ESTADO)
,COMCOE.ID COMCOE_ID
,COMCOE.FECHA COMCOE_FECHA
,COMCOE.ESTADO COMCOE_ESTADO
,COMCOE.MOTIVO COMCOE_MOTIVO
,(SELECT c.rv_abbreviation FROM cg_ref_codes c WHERE c.rv_domain = 'COM_CONTRATACIONES_EST.ESTADO' AND c.rv_low_value = comcoe.ESTADO)
,COMECC.CODIGO COMECC_CODIGO
,COMECC.NOMBRE COMECC_NOMBRE
FROM COM_ADJUDICACIONES COMADJ
,COM_ORDENES_COMPRAS COMOCM
,COM_CONTRATACIONES COMCON
,COM_PEDIDOS COMPED
,COM_PROVEEDORES COMPRV
,COM_ORDENES_COMPRAS_EST COMOCE
,COM_DOMICILIOS COMDOM
,COM_CONTRATACIONES_TIPOS COMCTT
,COM_CONTRATANTES COMECO
,COM_PEDIDOS_EST COMPEE
,COM_CONTRATACIONES_EST COMCOE
,COM_CONTRATANTES_CAT COMECC
WHERE comocm.segorg_id = seg_pkg.obtn_orgusu (NVL (v ('APP_USER'), USER))
AND comocm.comcon_id = comcon.ID
AND comocm.comadj_id = comadj.ID
AND comocm.comped_id = comped.ID
AND comocm.comprv_id = comprv.ID
AND comocm.comoce_id = comoce.ID
AND comped.comdom_id = comdom.ID
AND comped.comeco_id = comeco.ID
AND comcon.comctt_id = comctt.ID
AND comped.compee_id = compee.ID
AND comcon.comcoe_id = comcoe.ID
AND comeco.comecc_id = comecc.ID
;
 
